name: coveralls with hatch

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        default: "3.10"
    secrets:
      coveralls-repo-token:
        required: true

jobs:
  coveralls:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ input.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir hatch

      - name: Create environment
        run: |
          hatch -v env create test

      - name: Run coverage
        run: |
          hatch -v run test:coverage run -m pytest
          hatch -v run test:coverage json
          hatch -v run test:coverage report

      - name: Upload to coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls-repo-token }}
        run: |
          hatch -v run test:coveralls --service=github
