name: publish with hatch

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        default: "3.10"
      hatch-index-repo:
        required: true
        type: string
        default: "test"
    secrets:
      hatch-index-auth:
        required: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir hatch

      - name: Create environment
        run: |
          hatch -v env create build

      - name: Build package
        run: |
          hatch -v -e build build

      - name: Publish package
        env:
          HATCH_INDEX_REPO: ${{ inputs.hatch-index-repo }}
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.hatch-index-auth }}
        run: |
          hatch -v -e build publish
